FROM python:3.6
EXPOSE 8000
ENV BILLING_DB_USER postgres

RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - 
RUN apt-get update \
	&& apt-get install -y build-essential nodejs

#RUN apt-get update \
#    && apt-get install -y  nodejs npm \
#    && apt-get install -y --no-install-recommends \
#    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
	&& apt-get install -y python-dev libpq-dev postgresql-contrib

#RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN npm -g install bower

RUN pip install virtualenv
ADD requirements.txt .
RUN pip install -r requirements.txt

RUN mkdir /usr/src/env
RUN virtualenv -p /usr/local/bin/python /usr/src/env \
    && chmod +x /usr/src/env/bin/activate

VOLUME ["/usr/src/app"]
WORKDIR /usr/src/app

ENTRYPOINT bash -c "apt-get update && apt-get upgrade -y && ./server_startup"
